== Do you know, that I know, that you know, that I know...?

At the age of 'bout ten every day after school I used to do my homework at my Granny's
place. Also attending afternoon drama courses days quickly turned into dark evenings,
when I finally finished all the learning and made it back home to my parents.
Granny always insisted, that I please-please give her a ring, as soon as I arrive home, so
she could be certain, nothing happened to me on the long way home. She wouldn't
answer the phone of course, I only had to let it ring twice and hang up, to which she
would reply with her own two ringings, so I also knew, she'd heard it.
The walk home was quite a long and boring one, so I had plenty of time to do some
thinking. And boy I did... I just couldn't wrap my head around one specific issue, namely:
– How on earth does Granny know, it was me ringing,
(back then, phones did not display caller or number – getting older, eh?)
– how am I supposed to know, if it was her ringing me back,
– or how does she know, if I heard her response?
I was puzzled: Shouldn't I ring her back once again, so she'd really know it was me? Then
again, does that really solve anything? Can we both at the same time be certain?
I had to realize, I couldn't fundamentally change the setup how hard I ever tried. But then
again, wouldn't like a hundred rings back'n'forth settle the problem for sure? (I mean
even the two felt more or less enough...)
Is there an other way, through delays, timing, patterns, or any other trick for both of us to
be certain. I could never figure it out.
Turning older, every now and then I remembered those long evening walks, so these
questions – bit more general sure, but – returned to haunt me:
- Can you know, that I know, that you know, that I know...?
Until one day I read about a specific scientific problem, that of the Bizantine generals',
and realized that what I suspected back when I was ten was correct: There wasn't ever a
way for our little telephone-ringing ritual to lead to a perfect consensus between Granny
and me... it was impossible all along...
Hi everyone, with this first article, I would like to take the most persistent ones of you to a
journey, during which I hope to present you the most unbelievable invention of our
lifetime, maybe even one of the entire human history: Bitcoin.
I will try to explain the most important aspects and consequences of this extraordinary
invention (network, technology, phenomenon) plain and simple, but definitely not
dumbed down, while shedding light on fallacies, misunderstandings even blatant BS you
must already have heard and read about Bitcoin from so called expertsall over the press.
Belive me, you need to understand it, and understand it now.
I predict: we are about to experience a change in our way of life, of a scope, depth and
scale never seen before, thanks mostly to Bitcoin.
I will try to come up with new articles on a regular basis. I will touch many different topics,
and may even uncomfort some of you along the way, but I will do it with the best
intention. Please do not accept anything I write on face value: be doubtful, research, ask.
I could be and likely am wrong about many things, but I'll give it a try.
So this will be a bumpy ride!
You can send me feedback to my private email address.
See you soon... Szilárd