== Tudod, hogy én tudom, hogy Te tudod...?
szerző: sziller - http://sziller.eu

____
Felsős lehettem, általánosban. Hatodik óra után minden nap Nagyimhoz mentem ebédelni, házit írni. Volt egy csomó
délutáni különórám, így aztán Nagymamámtól legtöbbször nem hazaindultam, hanem edzésre, színjátszó szakkörre vagy
épp rajzolni. Általában késő estére értem haza a szüleimhez.

Nagyim persze ragaszkodott hozzá, hogy amint hazaértem, mindenképpen csörgessem meg telefonon, hogy tudja:
nem lett semmi bajom. Persze sose vette fel a telefont, én pedig csak egy-két csengetést vártam és letettem.
Utána természetesen ő csörrentett meg minket, hogy mi is tudjuk: hallotta, megnyugodott és mi is megnyugodhatunk,
hogy ő megnyugodott.

Azt nem állítanám, hogy izgalmas vidéken laktunk, sőt... borzasztóan untam ezeket az esti sétákat. Volt időm
gondolkodni, és bizony agyaltam is, ezerrel. Képtelen voltam rájönni például, hogy mitől működik
ez a kis telefonos szertartás:

* Honnan a fenéből tudta Nagyanyám, hogy én csörrentettem meg, és nem téves hívás volt? Vagy hogy nem egy barátnője
próbálkozott? +
(akkoriban analóg telefonokat használtunk, 3 kilós, piros bakelitkockákat. Ha leejtetted őket, nem a telefon tört el,
hanem a járólap. És nem, nem írta ki a hívószámot. Kijelzője se volt! – öregszünk, mi?)
* És én tudni fogom, hogy ő csörgött ránk?
* Na és Nagyim miből tudná, hogy mi hallottuk az ő válaszát?

Folyton ezen agyaltam: Nem kéne még egyszer visszacsörögnöm, hogy Nagyi is tudja, hogy tényleg én hívtam először és hogy
biztos legyen benne, hogy tudjuk, hogy megnyugodott? Viszont igazából megold ez valamit, vagy megint csak eltoltuk
a problémát? Van egyáltalán lehetőség rá, hogy mindketten teljesen biztosak legyünk a dolgunkban?
Be kellett ismernem, képtelen vagyok tökéletes egyetértést kicsöngetgetni Nagyival. Másrészről viszont nem lenne elég
például száz oda-vissza? Azért ha belegondolok: aggódó Nagyim már egy viszonzott csörgéssel is tökéletesen megelégedett.

Teltek-múltak az évek, ritkultak a hajszálak, felszedtem ezt-azt. Nagyi sincs már.

Sokszor eszembe jut. És bizony újra és újra beugrottak a telefonálgatások is. Még mindig kísértett a kérdés,
ezúttal már sokkal általánosabban. Nem lehetne valamilyen módon, késleltetésekkel, időzítéssel, mintákkal
vagy bármilyen más trükkel teljes bizonyossággal meggyőzni a másikat és egyetértésre jutni? - Nos, sose jöttem rá.

Aztán egy nap olvastam egy számítástechnikai problémáról, a bizánci hadvezér gondterhelt tervezgetéséről és el kellett
fogadnom, hogy amit az unalmas sétákon sejtettem, az tényleg úgy van: Nagyival soha sem tudtunk volna tökéletes
konszenzust létrehozni. A mi kis rituálénk úgy-ahogy működött, de tökéletesen sosem lehettünk biztosak benne,
hogy mind a ketten ugyanazt gondoljuk a világról.

Az első pillanattól lehetetlen volt.
____

=== Sziasztok!
Ezzel a kis sztorival egy cikksorozatot indítok útnak. Részletesen be fogom nektek mutatni korunk - ha nem az
egész történelem - egyik legnagyobb hatású találmányát, a Bitcoint.

Meg fogom próbálni ennek a sokrétű és rendkívüli találmánynak alapvető koncepcióit, és lényegi következményeit
érthetően, de semmiképpen sem lebutítva átbeszélni, miközben rávilágítok nagycsomó tévedésre, félreértésre.
Útközben eloszlatunk majd jónéhány szándékos félrevezetésből következő tévhitet is.

*A Bitcoint meg kell érteni!*

Meghatározó, életünk számos területét alapjaiban átalakító változásokat látunk és fogunk a közeljövőben megélni.
Változásokat, melyek nagyrészét a Bitcoinnak köszönhetjük.
Hetente tervezek logikusan, egymásra épülő cikkekkel előállni. Számos témát szeretnék tárgyalni, és biztosan lesznek
írások, amik sokatok alapvető világlátását is megpiszkálja majd. Készakarva, de jószándékkal.
Semmit ne nyeljetek be, csak mert leírtam: tessék kételkedni, utánanézni, kérdezősködni!
Nyilván lesz egy rakás tévedésem, de azért csak hozzálátok.

Rázós menet lesz...!